# Generated by Django 3.2.9 on 2023-10-24 18:14

import backend.storages
import damage_report.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReportStatus',
            fields=[
                ('damage_status', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('not_fixed', models.BooleanField(default=False, help_text='Η επιλογή αντιστοιχεί στην κατάσταση που δεν έχει παρθεί ενέργεια για την αποκατάσταση της ζημιάς.', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Καταστάσεις Ζημιών',
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('damage_type', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('default_selected', models.BooleanField(default=False, help_text='Η επιλογή θα είναι προεπιλεγμένη στην εφαρμογή του χρήστη.', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Τύποι Ζημιών',
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=backend.storages.OverwriteStorage, upload_to=damage_report.models.DamageReport.get_image_path)),
                ('description', models.TextField(help_text='Περιγραφή της ζημιάς από τον χρήστη.', max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('damage_report_notes', models.TextField(help_text='Σημειώσεις για την επισκευή της ζημιάς (από την διοίκηση της σχολής).', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_time', models.DateTimeField(blank=True, help_text='Ημερομηνία που επιδιορθώθηκε η βλάβη (εάν έχει επιδιορθωθεί).', null=True)),
                ('towards_fixing_time', models.DateTimeField(blank=True, help_text='Ημερομηνία που τέθηκε προς επισκευή η βλάβη (εάν έχει τεθεί).', null=True)),
                ('damage_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damage_report.damagereportstatus')),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damage_report.damagetype')),
            ],
            options={
                'verbose_name_plural': 'Αναφορές Ζημιών',
            },
        ),
    ]
