# Generated by Django 3.2.9 on 2023-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereportstatus',
            name='not_fixed',
        ),
        migrations.RemoveField(
            model_name='damagetype',
            name='default_selected',
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='damagereportstatus',
            name='damage_status',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='damagetype',
            name='damage_type',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
